name: Lighthouse CI

on:
  push:
    branches: [dev, main]
  pull_request:

permissions:
  contents: read

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Install Lighthouse CI
        run: pnpm add -D @lhci/cli

      - name: Serve built app
        run: npx serve dist --listen 8080 &
      
      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 2
          done
          echo "Server did not start in time"
          exit 1

      - name: Run Lighthouse CI
        run: npx lhci autorun --upload.target=temporary-public-storage

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci